In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# -*- coding: utf-8 -*-
import argparse
import math
import sys
import time
import copy
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import keras
from keras.models import Sequential, Model
from keras.layers import Dense, Dropout, Flatten, Activation, BatchNormalization#, regularizers
from keras.layers.noise import GaussianNoise
from keras.layers import Conv1D, MaxPooling1D
from keras import backend as K
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.utils.np_utils import to_categorical
#K.set_image_dim_ordering('th')
#print(K.image_data_format())

## required for efficient GPU use
#import tensorflow as tf
#from keras.backend import tensorflow_backend
#config = tf.ConfigProto(gpu_options=tf.GPUOptions(allow_growth=True))
#session = tf.Session(config=config)
#tensorflow_backend.set_session(session)
## required for efficient GPU use

import os
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np # linear algebra

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
model_path='/content/drive/MyDrive/Colab Notebooks/CSCI 356 Term Project/Shallow CNN Model/results/cnn_shallow_train+test+.h5'

# prepare callbacks
callbacks = [
    EarlyStopping(
        monitor='val_acc', 
        patience=10,
        mode='max',
        verbose=1),
    ModelCheckpoint(model_path,
        monitor='val_acc', 
        save_best_only=True, 
        mode='max',
        verbose=0)
]

In [4]:
# get data

class dataset:
    kdd_train_2labels = pd.read_pickle("/content/drive/MyDrive/Colab Notebooks/CSCI 356 Term Project/KDD Dataset Preprocessing/kdd_train_2labels.pkl") #train+
    kdd_test_2labels = pd.read_pickle("/content/drive/MyDrive/Colab Notebooks/CSCI 356 Term Project/KDD Dataset Preprocessing/kdd_test_2labels.pkl") #test+
    
from sklearn import model_selection as ms
from sklearn import preprocessing as pp

class preprocess:
    
    output_columns_2labels = ['is_Normal','is_Attack']
    
    x_input = dataset.kdd_train_2labels.drop(output_columns_2labels, axis = 1)
    y_output = dataset.kdd_train_2labels.loc[:,output_columns_2labels]

    x_test_input = dataset.kdd_test_2labels.drop(output_columns_2labels, axis = 1)
    y_test = dataset.kdd_test_2labels.loc[:,output_columns_2labels]
    
    ss = pp.StandardScaler()

    x_train = ss.fit_transform(x_input)
    x_test = ss.fit_transform(x_test_input)

    y_train = y_output.values
    y_test = y_test.values
    
    print('x_train shape: {}'.format(x_train.shape))
    print('y_train shape: {}'.format(y_train.shape))
    print('x_test_ shape: {}'.format(x_test.shape))
    print('y_test_ shape: {}'.format(y_test.shape))

x_train shape: (125973, 122)
y_train shape: (125973, 2)
x_test_ shape: (22544, 122)
y_test_ shape: (22544, 2)


In [5]:
#reshape data
X_train = np.reshape(preprocess.x_train, (preprocess.x_train.shape[0], preprocess.x_train.shape[1], 1))
X_test = np.reshape(preprocess.x_test, (preprocess.x_test.shape[0], preprocess.x_test.shape[1], 1))

print('train shape after reshape: {}'.format(X_train.shape))
print('test shape after reshape: {}'.format(X_test.shape))

train shape after reshape: (125973, 122, 1)
test shape after reshape: (22544, 122, 1)


In [6]:
#size of parameters
batch_size = 32
num_classes = 2
epochs = 5
filter_size= 3
droprate=0.50

In [7]:
#Start Neural Network
model = Sequential()

#convolution 1st layer
model.add(Conv1D(64, kernel_size=(filter_size), padding="same",
                 activation='relu',
                 input_shape=(122, 1)))
model.add(BatchNormalization())
model.add(Dropout(droprate))
model.add(MaxPooling1D(strides=2))

#FCN layer
model.add(Flatten())
model.add(Dense(64,use_bias=False))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(droprate))
model.add(Dense(2))
model.add(Activation('softmax'))

model.compile(loss="binary_crossentropy", optimizer="Adam", metrics=['accuracy'])

model.summary()

Instructions for updating:
Colocations handled automatically by placer.
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 122, 64)           256       
                                                                 
 batch_normalization (BatchN  (None, 122, 64)          256       
 ormalization)                                                   
                                                                 
 dropout (Dropout)           (None, 122, 64)           0         
                                                                 
 max_pooling1d (MaxPooling1D  (None, 61, 64)           0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 3904)              0         
                                                  

In [8]:
#Save Model=ON
history = model.fit(X_train, preprocess.y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(X_test, preprocess.y_test),shuffle=True,callbacks=callbacks)

score = model.evaluate(X_test, preprocess.y_test,verbose=0)

#print loss and accuracy
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Train on 125973 samples, validate on 22544 samples
Epoch 1/5
125952/125973 [============================>.] - ETA: 0s - loss: 0.0684 - acc: 0.9766

/usr/local/lib/python3.7/dist-packages/keras/engine/training_v1.py:2057: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates = self.state_updates


125973/125973 [==============================] - 71s 564us/sample - loss: 0.0684 - acc: 0.9766 - val_loss: 0.8868 - val_acc: 0.8162
Epoch 2/5
125973/125973 [==============================] - 71s 563us/sample - loss: 0.0464 - acc: 0.9837 - val_loss: 0.9397 - val_acc: 0.8052
Epoch 3/5
125973/125973 [==============================] - 71s 561us/sample - loss: 0.0411 - acc: 0.9854 - val_loss: 0.9012 - val_acc: 0.8044
Epoch 4/5
125973/125973 [==============================] - 69s 544us/sample - loss: 0.0390 - acc: 0.9868 - val_loss: 0.9178 - val_acc: 0.8081
Epoch 5/5
125973/125973 [==============================] - 68s 543us/sample - loss: 0.0374 - acc: 0.9870 - val_loss: 0.9109 - val_acc: 0.8093
Test loss: 0.9109121380628974
Test accuracy: 0.80930626


In [10]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)
print(y_pred)
y_pred = np.argmax(y_pred, axis=1)
print(y_pred)

predict_proba = model.predict(X_test)
predict_classes = np.argmax(predict_proba, axis=1)

target_names = ['Normal', 'Attack']
print(classification_report(np.argmax(preprocess.y_test, axis=1), y_pred, target_names=target_names, digits=4))
print(confusion_matrix(np.argmax(preprocess.y_test, axis=1), y_pred))

[[9.6172313e-17 1.0000000e+00]
 [6.4500631e-15 1.0000000e+00]
 [9.9997926e-01 2.0740381e-05]
 ...
 [1.6372950e-03 9.9836272e-01]
 [1.0000000e+00 9.7919728e-11]
 [5.8600250e-07 9.9999940e-01]]
[1 1 0 ... 1 0 1]
              precision    recall  f1-score   support

      Normal     0.7186    0.9159    0.8054      9711
      Attack     0.9196    0.7287    0.8131     12833

    accuracy                         0.8093     22544
   macro avg     0.8191    0.8223    0.8092     22544
weighted avg     0.8331    0.8093    0.8098     22544

[[8894  817]
 [3482 9351]]
